/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapedidos;

import java.awt.Component;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chino
 */
public class Principal extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private String[] filaTabla;
    private Comprador comprador;
    private DefaultComboBoxModel modelo;
    private DefaultComboBoxModel modeloColores;

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        activarPaneles("orden", false);
        activarPaneles("descripcion", false);
        activarPaneles("detalles", false);
        this.modeloTabla = new DefaultTableModel();

        String titulosTabla[] = {"COD. PRODUCTO", "PRODUCTO", "CANTIDAD", "COLOR", "TALLA", "PRECIO"};
        modeloTabla = new DefaultTableModel(null, titulosTabla);
        jtblPedidos.setModel(modeloTabla);
        this.filaTabla = new String[6];
        jbtnEditar.setEnabled(false);
        jbtnEliminar.setEnabled(false);
        //
        Object[] fila = {"1801", "Camiseta", "20", "Rojo", "S", "7.50"};
        modeloTabla.addRow(fila);
        Object[] fila2 = {"1801", "Camisa", "16", "Azul", "L", "10.50"};
        modeloTabla.addRow(fila2);
        jtblPedidos.setModel(modeloTabla);
        //

        //ComboBox producto
        String[] ropa = {"Camiseta", "Camisa", "Jean", "Pantalon", "Blusa"};
        modelo = new DefaultComboBoxModel(ropa);
        jcbxProducto.setModel(modelo);

        //[nombreProducto,cantidadProducto,color(null),cantidad,color,cantidad,color,cantidad]
    }

    public void activarPaneles(String nombrePanel, boolean activado) {
        //nombrePanel -> orden, descripcion, detalles
        if (nombrePanel.equals("datos")) {
            for (Component component : jPanel1.getComponents()) {
                component.setEnabled(activado);
            }
        }
        if (nombrePanel.equals("orden")) {
            for (Component component : jPanel4.getComponents()) {
                component.setEnabled(activado);
            }
        }
        if (nombrePanel.equals("descripcion")) {
            for (Component component : jPanel5.getComponents()) {
                component.setEnabled(activado);
            }
        }
        if (nombrePanel.equals("detalles")) {
            for (Component component : jPanel6.getComponents()) {
                component.setEnabled(activado);
            }
        }
    }

    public boolean datosCompletos() {
        if (jtxtCedula.getText().equals("") || jtxtNombre.getText().equals("") || jtxtApellido.getText().equals("")
                || jtxtDireccion.getText().equals("") || jtxtTelefono.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpiarIngresoUsuario() {
        jtxtCedula.setText("");
        jtxtNombre.setText("");
        jtxtApellido.setText("");
        jtxtDireccion.setText("");
        jtxtTelefono.setText("");
    }

    public void actualizarTabla() {
        for (int j = 0; j < this.comprador.getProductos().size(); j++) {
            Object[] fila = {this.comprador.getProductos().get(j).getCodProducto(), this.comprador.getProductos().get(j).getNombre(),
                this.comprador.getProductos().get(j).getCantidad(), this.comprador.getProductos().get(j).getColor(),
                this.comprador.getProductos().get(j).getTalla(), this.comprador.getProductos().get(j).getPrecio()};
            modeloTabla.addRow(fila);
        }
        jtblPedidos.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jtxtCedula = new componentespropios.jtxtSoloNumeros();
        jtxtTelefono = new componentespropios.jtxtSoloNumeros();
        jtxtNombre = new miscomponentes.SoloLetras();
        jtxtApellido = new miscomponentes.SoloLetras();
        jbtnGuardarUsuario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jbtnGuardarDescripcion = new javax.swing.JButton();
        jcbxTallaDescripcion = new javax.swing.JComboBox<>();
        jtxtCantidadDescripcion = new componentespropios.jtxtSoloNumeros();
        jcbxColorDescripcion = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPedidos = new javax.swing.JTable();
        jbtnEditar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbxProducto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jsldCantidad = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jchkAmarillo = new javax.swing.JCheckBox();
        jchkAzul = new javax.swing.JCheckBox();
        jchkRojo = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jtxtCantidadAmarillo = new componentespropios.jtxtSoloNumeros();
        jtxtCantidadAzul = new componentespropios.jtxtSoloNumeros();
        jbtnAceptar = new javax.swing.JButton();
        jtxtCantidadRojo = new componentespropios.jtxtSoloNumeros();
        jtxtCantidadTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtCodProducto = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(454, 340));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cédula:");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel3.setText("DATOS");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección:");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Télefono:");

        jtxtDireccion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jtxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionActionPerformed(evt);
            }
        });

        jtxtCedula.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jtxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCedulaActionPerformed(evt);
            }
        });
        jtxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyTyped(evt);
            }
        });

        jtxtTelefono.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jtxtNombre.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N

        jtxtApellido.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jbtnGuardarUsuario.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jbtnGuardarUsuario.setText("Guardar");
        jbtnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtDireccion)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGuardarUsuario))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel12.setText("DESCRIPCION");

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel14.setText("Talla");

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel15.setText("Cantidad");

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel16.setText("Color");

        jbtnGuardarDescripcion.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jbtnGuardarDescripcion.setText("GUARDAR");
        jbtnGuardarDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarDescripcionActionPerformed(evt);
            }
        });

        jcbxTallaDescripcion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jcbxTallaDescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        jcbxTallaDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxTallaDescripcionActionPerformed(evt);
            }
        });

        jtxtCantidadDescripcion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jcbxColorDescripcion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jcbxColorDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxColorDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxTallaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jtxtCantidadDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbxColorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jbtnGuardarDescripcion)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel12)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCantidadDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxTallaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxColorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnGuardarDescripcion)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DETALLES DE ORDEN");

        jtblPedidos.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jtblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtblPedidos.setRowHeight(28);
        jtblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPedidos);

        jbtnEditar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jbtnEliminar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jButton5.setText("FINALIZAR COMPRA");

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel22.setText("TOTAL:");

        jTextField1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(241, 241, 241))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(31, 31, 31))
        );

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        jLabel23.setText("SISTEMA DE PEDIDOS");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel7.setText("ORDEN");

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Producto:");

        jcbxProducto.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Cantidad:");

        jsldCantidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jsldCantidad.setMajorTickSpacing(10);
        jsldCantidad.setMaximum(50);
        jsldCantidad.setMinorTickSpacing(5);
        jsldCantidad.setPaintLabels(true);
        jsldCantidad.setPaintTicks(true);
        jsldCantidad.setSnapToTicks(true);
        jsldCantidad.setToolTipText("");
        jsldCantidad.setValue(25);
        jsldCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldCantidadStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel10.setText("Color");

        jchkAmarillo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jchkAmarillo.setText("Amarillo");
        jchkAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAmarilloActionPerformed(evt);
            }
        });

        jchkAzul.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jchkAzul.setText("Azul");
        jchkAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAzulActionPerformed(evt);
            }
        });

        jchkRojo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jchkRojo.setText("Rojo");
        jchkRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkRojoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel11.setText("Cantidad");

        jtxtCantidadAmarillo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jtxtCantidadAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadAmarilloActionPerformed(evt);
            }
        });

        jtxtCantidadAzul.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jbtnAceptar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jtxtCantidadRojo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        jtxtCantidadTotal.setEditable(false);
        jtxtCantidadTotal.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jtxtCantidadTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadTotalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Id producto:");
        jLabel17.setToolTipText("");

        jtxtCodProducto.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkAzul)
                            .addComponent(jchkAmarillo)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxtCantidadAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11)
                                            .addComponent(jtxtCantidadAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtCantidadRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcbxProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jsldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtCantidadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jchkRojo)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jbtnAceptar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jsldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCantidadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkAmarillo)
                    .addComponent(jtxtCantidadAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkAzul)
                    .addComponent(jtxtCantidadAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkRojo)
                    .addComponent(jtxtCantidadRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCedulaActionPerformed

    private void jtxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionActionPerformed

    private void jtxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyTyped
        // TODO add your handling code here:
        this.controlCedula(evt);
    }//GEN-LAST:event_jtxtCedulaKeyTyped

    private void jchkAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAzulActionPerformed
        if (jchkAzul.isSelected()) {
            jtxtCantidadAzul.setEnabled(true);
        } else {
            jtxtCantidadAzul.setEnabled(false);
            jtxtCantidadAzul.setText("");
        }
    }//GEN-LAST:event_jchkAzulActionPerformed

    private void jchkRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkRojoActionPerformed
        if (jchkRojo.isSelected()) {
            jtxtCantidadRojo.setEnabled(true);
        } else {
            jtxtCantidadRojo.setEnabled(false);
            jtxtCantidadRojo.setText("");
        }
    }//GEN-LAST:event_jchkRojoActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        boolean success = false;
        this.comprador.setCantProductos(Integer.valueOf(jtxtCantidadTotal.getText()));

        if (!jchkAmarillo.isSelected() && !jchkAzul.isSelected() && !jchkRojo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Seleccione al menos un color con su respectiva cantidad");
        } else {

            if (jchkAmarillo.isSelected() && !jchkAzul.isSelected() && !jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAmarillo.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items no coincide con la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAmarillo.getText()), "Amarillo", "S");
                    success = true;
                }
            }
            if (!jchkAmarillo.isSelected() && jchkAzul.isSelected() && !jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAzul.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAzul.getText()), "Azul", "S");
                    success = true;
                }
            }
            if (!jchkAmarillo.isSelected() && !jchkAzul.isSelected() && jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadRojo.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadRojo.getText()), "Rojo", "S");
                    success = true;
                }
            }

            if (jchkAmarillo.isSelected() && jchkAzul.isSelected() && !jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAmarillo.getText())) || this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAzul.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), jtxtCantidadAmarillo.getTextAsInteger(), "Amarillo", "S");
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), jtxtCantidadAzul.getTextAsInteger(), "Azul", "S");
                    success = true;
                }
            }
            if (jchkAmarillo.isSelected() && !jchkAzul.isSelected() && jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAmarillo.getText()) + this.getTextAsInteger(jtxtCantidadRojo.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAmarillo.getText()), "Amarillo", "S");
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadRojo.getText()), "Rojo", "S");
                    success = true;
                }
            }
            if (!jchkAmarillo.isSelected() && jchkAzul.isSelected() && jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAzul.getText()) + this.getTextAsInteger(jtxtCantidadRojo.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAzul.getText()), "Azul", "S");
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadRojo.getText()), "Rojo", "S");
                    success = true;
                }
            }
            if (jchkAmarillo.isSelected() && jchkAzul.isSelected() && jchkRojo.isSelected()) {
                if (this.comprador.cantidadMaxima(this.getTextAsInteger(jtxtCantidadAmarillo.getText()) + this.getTextAsInteger(jtxtCantidadAzul.getText()) + this.getTextAsInteger(jtxtCantidadRojo.getText()))) {
                    JOptionPane.showMessageDialog(null, "La cantidad de items supera la cantidad de productos seleccionados");
                } else {
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAmarillo.getText()), "Amarillo", "S");
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadAzul.getText()), "Azul", "S");
                    this.comprador.comprarProducto(jtxtCodProducto.getText(), jcbxProducto.getSelectedItem().toString(), Integer.valueOf(jtxtCantidadRojo.getText()), "Rojo", "S");
                    success = true;
                }
            }
            if (this.getTextAsInteger(jtxtCantidadAmarillo.getText()) + this.getTextAsInteger(jtxtCantidadAzul.getText()) + this.getTextAsInteger(jtxtCantidadRojo.getText()) == this.comprador.getCantProductos()) {
                if (success) {
                    jcbxColorDescripcion.removeAllItems();
                    for (int i = 0; i < this.comprador.getProductos().size(); i++) {
                        jcbxColorDescripcion.addItem(this.comprador.getProductos().get(i).getColor());
                    }

                    jchkAmarillo.setSelected(false);
                    jchkAzul.setSelected(false);
                    jchkRojo.setSelected(false);
                    jtxtCantidadAmarillo.setText("");
                    jtxtCantidadAzul.setText("");
                    jtxtCantidadRojo.setText("");
                    this.activarPaneles("orden", false);
                    this.activarPaneles("descripcion", true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe asignar un color a la cantidad total seleccionada anteriormente" + "\n******************** Faltan " + (this.comprador.getCantProductos() - (this.getTextAsInteger(jtxtCantidadAmarillo.getText()) + this.getTextAsInteger(jtxtCantidadAzul.getText()) + this.getTextAsInteger(jtxtCantidadRojo.getText()))) + " productos por asignar ********************");
            }
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed
    public int getTextAsInteger(String text) {
        Integer retorno = 0;
        if (text.isEmpty()) {
            retorno = 0;
        } else {
            retorno = Integer.valueOf(text);
        }
        return retorno;
    }

    public void limpiarOrden() {
        jtxtCantidadAmarillo.setEnabled(false);
        jtxtCantidadAmarillo.setText("");
        jtxtCantidadAzul.setEnabled(false);
        jtxtCantidadAzul.setText("");
        jtxtCantidadRojo.setEnabled(false);
        jtxtCantidadRojo.setText("");
    }

    public Double precioPorTalla(String text) {
        if (text.equals("S")) {
            return 5.50;
        } else if (text.equals("M")) {
            return 8.50;
        } else {
            return 12.50;
        }
    }
    private void jbtnGuardarDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarDescripcionActionPerformed
        boolean success = false;
        String mensajeProductos = "";
        for (int j = 0; j < this.comprador.getProductos().size(); j++) {
            if (jcbxColorDescripcion.getSelectedItem().toString().equals(this.comprador.getProductos().get(j).getColor())) {
                if (this.comprador.getProductos().get(j).getCantidad() > 0 && this.comprador.getProductos().get(j).getCantidad() >= jtxtCantidadDescripcion.getTextAsInteger()) {
                    Object[] fila = {this.comprador.getProductos().get(j).getCodProducto(), this.comprador.getProductos().get(j).getNombre(),
                        jtxtCantidadDescripcion.getTextAsInteger(), jcbxColorDescripcion.getSelectedItem().toString(),
                        jcbxTallaDescripcion.getSelectedItem().toString(), this.precioPorTalla(jcbxTallaDescripcion.getSelectedItem().toString()) * jtxtCantidadDescripcion.getTextAsInteger()};
                    modeloTabla.addRow(fila);
                    this.comprador.getProductos().get(j).setCantidad(this.comprador.getProductos().get(j).getCantidad() - jtxtCantidadDescripcion.getTextAsInteger());
                }
            }
        }
        jtblPedidos.setModel(modeloTabla);

        for (int j = 0; j < this.comprador.getProductos().size(); j++) {
            if (this.comprador.getProductos().get(j).getCantidad() == 0) {
                success = true;
            } else {
                mensajeProductos += "\n*******************| " + this.comprador.getProductos().get(j).getCantidad() + " productos del color " + this.comprador.getProductos().get(j).getColor() + " por asignar su talla |*******************";
                success = false;
            }
        }
        if (success) {
            this.activarPaneles("orden", true);
            this.activarPaneles("descripcion", false);
            this.limpiarOrden();
        } else {
            JOptionPane.showMessageDialog(null, mensajeProductos);
        }
        jtxtCantidadDescripcion.setText("");
    }//GEN-LAST:event_jbtnGuardarDescripcionActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        int fila = jtblPedidos.getSelectedRow();
        ventanaEditar editar = new ventanaEditar(this.comprador);
        editar.setVisible(true);
        editar.totalPedidos();
        editar.validarDatos(filaTabla);
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPedidosMouseClicked
        jbtnEditar.setEnabled(true);
        jbtnEliminar.setEnabled(true);
        JTable tabla = (JTable) evt.getSource();
        int row = tabla.getSelectedRow();
        for (int i = 0; i < filaTabla.length; i++) {
            filaTabla[i] = tabla.getModel().getValueAt(row, i).toString();
        }
    }//GEN-LAST:event_jtblPedidosMouseClicked

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        int fila = jtblPedidos.getSelectedRow();
        modeloTabla.removeRow(fila);
        jtblPedidos.setModel(modeloTabla);
        jbtnEditar.setEnabled(false);
        jbtnEliminar.setEnabled(false);
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarUsuarioActionPerformed
        if (this.datosCompletos() == false) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            this.limpiarIngresoUsuario();
        } else {
            this.comprador = new Comprador(jtxtCedula.getText(), jtxtNombre.getText(),
                    jtxtApellido.getText(), jtxtDireccion.getText(), jtxtTelefono.getText());
            JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente");
            activarPaneles("orden", true);
            activarPaneles("datos", false);
            jtxtCantidadAmarillo.setEnabled(false);
            jtxtCantidadAzul.setEnabled(false);
            jtxtCantidadRojo.setEnabled(false);
        }

    }//GEN-LAST:event_jbtnGuardarUsuarioActionPerformed


    private void jsldCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldCantidadStateChanged
        jtxtCantidadTotal.setText(String.valueOf(jsldCantidad.getValue()));
    }//GEN-LAST:event_jsldCantidadStateChanged

    private void jcbxTallaDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxTallaDescripcionActionPerformed
        // TODO add your handling code here:
        System.out.println(this.comprador.getProductos());
    }//GEN-LAST:event_jcbxTallaDescripcionActionPerformed

    private void jtxtCantidadAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadAmarilloActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtCantidadAmarilloActionPerformed

    private void jchkAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAmarilloActionPerformed
        // TODO add your handling code here:
        if (jchkAmarillo.isSelected()) {
            jtxtCantidadAmarillo.setEnabled(true);
        } else {
            jtxtCantidadAmarillo.setEnabled(false);
            jtxtCantidadAmarillo.setText("");
        }
    }//GEN-LAST:event_jchkAmarilloActionPerformed

    private void jtxtCantidadTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadTotalActionPerformed

    private void jcbxColorDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxColorDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxColorDescripcionActionPerformed

    public void controlCedula(java.awt.event.KeyEvent evt) {
        if (jtxtCedula.getText().length() >= 10) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardarDescripcion;
    private javax.swing.JButton jbtnGuardarUsuario;
    private javax.swing.JComboBox<String> jcbxColorDescripcion;
    private javax.swing.JComboBox<String> jcbxProducto;
    private javax.swing.JComboBox<String> jcbxTallaDescripcion;
    private javax.swing.JCheckBox jchkAmarillo;
    private javax.swing.JCheckBox jchkAzul;
    private javax.swing.JCheckBox jchkRojo;
    private javax.swing.JSlider jsldCantidad;
    private javax.swing.JTable jtblPedidos;
    private miscomponentes.SoloLetras jtxtApellido;
    private componentespropios.jtxtSoloNumeros jtxtCantidadAmarillo;
    private componentespropios.jtxtSoloNumeros jtxtCantidadAzul;
    private componentespropios.jtxtSoloNumeros jtxtCantidadDescripcion;
    private componentespropios.jtxtSoloNumeros jtxtCantidadRojo;
    private javax.swing.JTextField jtxtCantidadTotal;
    private componentespropios.jtxtSoloNumeros jtxtCedula;
    private javax.swing.JTextField jtxtCodProducto;
    private javax.swing.JTextField jtxtDireccion;
    private miscomponentes.SoloLetras jtxtNombre;
    private componentespropios.jtxtSoloNumeros jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
